### ISSUE TITLE
Bug: Tries to access property of None instance

### ISSUE THREAD

**Issue by rnowling-memphis** [memphisdev/memphis.py#152]
I created a producer for testing schemaverse.  It generates todo items in which 25% are bad in some way (missing key, wrong type, null value).  The message fails validation and a `MemphisSchemaError` exception is thrown.  In the handling of that exception, another exception is thrown because a line of code that attempts to access a property on a None object.

```
{'creation_timestamp': {'$date': 1684895034}, 'due_date': None, 'description': 'HARUOZTOJQPTRFDNVXTW', 'completed': False}
Sending message: {"creation_timestamp": {"$date": 1684895034}, "due_date": null, "description": "HARUOZTOJQPTRFDNVXTW", "completed": false}
Traceback (most recent call last):
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/memphis/producer.py", line 102, in validate_json_schema
    validate(
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: '_id' is a required property

Failed validating 'required' in schema:
    {'$id': 'https://memphis.dev/todo_item.schema.json',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     'description': 'An item in a todo checklist',
     'properties': {'_id': {'properties': {'$oid': {'type': 'string'}},
                            'type': 'object'},
                    'completed': {'type': 'boolean'},
                    'creation_timestamp': {'properties': {'$date': {'type': 'integer'}},
                                           'type': 'object'},
                    'description': {'type': 'string'},
                    'due_date': {'anyOf': [{'properties': {'$date': {'type': 'integer'}},
                                            'type': 'object'},
                                           {'type': 'null'}]}},
     'required': ['_id', 'description', 'creation_timestamp', 'completed'],
     'title': 'TodoItem',
     'type': 'object'}

On instance:
    {'completed': False,
     'creation_timestamp': {'$date': 1684895034},
     'description': 'HARUOZTOJQPTRFDNVXTW',
     'due_date': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/memphis/producer.py", line 156, in produce
    message = await self.validate_msg(message)
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/memphis/producer.py", line 39, in validate_msg
    message = self.validate_json_schema(message)
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/memphis/producer.py", line 108, in validate_json_schema
    raise MemphisSchemaError("Schema validation has failed: " + str(e))
memphis.exceptions.MemphisSchemaError: memphis: Schema validation has failed: '_id' is a required property

Failed validating 'required' in schema:
    {'$id': 'https://memphis.dev/todo_item.schema.json',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     'description': 'An item in a todo checklist',
     'properties': {'_id': {'properties': {'$oid': {'type': 'string'}},
                            'type': 'object'},
                    'completed': {'type': 'boolean'},
                    'creation_timestamp': {'properties': {'$date': {'type': 'integer'}},
                                           'type': 'object'},
                    'description': {'type': 'string'},
                    'due_date': {'anyOf': [{'properties': {'$date': {'type': 'integer'}},
                                            'type': 'object'},
                                           {'type': 'null'}]}},
     'required': ['_id', 'description', 'creation_timestamp', 'completed'],
     'title': 'TodoItem',
     'type': 'object'}

On instance:
    {'completed': False,
     'creation_timestamp': {'$date': 1684895034},
     'description': 'HARUOZTOJQPTRFDNVXTW',
     'due_date': None}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/test_schemaverse_producer.py", line 80, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/test_schemaverse_producer.py", line 65, in main
    await producer.produce(bytearray(msg, "utf-8"))
  File "/home/rnowling/Projects/memphis-example-solutions/mongodb-cdc-schemaverse-example/memphis-setup-testing/venv/lib/python3.9/site-packages/memphis/producer.py", line 220, in produce
    headers = headers.headers
AttributeError: 'NoneType' object has no attribute 'headers'
```

Script is:

```python
from __future__ import annotations
import asyncio
import datetime as dt
import json
import logging
import os
import random
import sys
import time

from memphis import Memphis, Headers, MemphisError, MemphisConnectError, MemphisHeaderError, MemphisSchemaError

STATION_KEY = "MEMPHIS_STATION"
USERNAME_KEY = "MEMPHIS_USERNAME"
PASSWORD_KEY = "MEMPHIS_PASSWORD"
HOST_KEY = "MEMPHIS_HOST"

DESCRIPTION_LENGTH = 20
ASCII_START = 65 # uppercase A
ASCII_END = 90 # uppercase Z

def generate_todo_items():
    while True:
        todo_item = {}

        # generate a todo item
        creation_timestamp = dt.datetime.now()
        due_date = int((creation_timestamp + dt.timedelta(days=3)).timestamp())
        description = "".join([chr(random.randint(ASCII_START, ASCII_END))
                               for i in range(DESCRIPTION_LENGTH)])
        completed = random.random() < 0.1

        todo_item["_id"] = { "$oid" : "abc25" }
        todo_item["creation_timestamp"] = { "$date" : int(creation_timestamp.timestamp()) }
        todo_item["due_date"] = None if random.random() >= 0.5 else { "$date" : due_date }
        todo_item["description"] = description
        todo_item["completed"] = completed

        # 25% of messages will be "bad"
        if random.random() < 0.25:
            r = random.random()
            key = random.choice(list(todo_item.keys()))
            if r < 0.3333: # drop required key
                del todo_item[key]
            elif r < 0.6666: # assign value of wrong type to key
                todo_item[key] = -5000
            else: # set item to null
                todo_item[key] = None

        yield todo_item

async def main():
    try:
        item_generator = generate_todo_items()

        memphis = Memphis()
        await memphis.connect(host=os.environ[HOST_KEY], username=os.environ[USERNAME_KEY], password=os.environ[PASSWORD_KEY])

        producer = await memphis.producer(station_name=os.environ[STATION_KEY], producer_name="test-producer")

        for item in item_generator:
            print(item)
            msg = json.dumps(item)
            print("Sending message: {}".format(msg))
            await producer.produce(bytearray(msg, "utf-8"))
            time.sleep(0.5)

    except (MemphisError, MemphisConnectError, MemphisHeaderError, MemphisSchemaError) as e:
        print(e)

    finally:
        await memphis.close()

if __name__ == "__main__":
    for key in [HOST_KEY, USERNAME_KEY, PASSWORD_KEY, STATION_KEY]:
        if key not in os.environ:
            logging.error("Expected environmental variable {} not set".format(key))
            sys.exit(1)

    asyncio.run(main())
```

Schema is:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://memphis.dev/todo_item.schema.json",
  "title": "TodoItem",
  "description": "An item in a todo checklist",
  "type": "object",
  "properties" : {
	  "_id" : {
		  "type" : "object",
		  "properties" : {
			  "$oid" : {
				  "type" : "string"
			  }
		  }
	  },
	  "description" : {
		  "type" : "string"
	  },
	  "creation_timestamp" : {
		  "type" : "object",
		  "properties" : {
			  "$date" : {
				  "type" : "integer"
			  }
		  }
	  },
	  "due_date" : {
	  		"anyOf" : [
				{
					"type" : "object",
					"properties" : {
						"$date" : {
							"type" : "integer"
						}
					}
				},
				{
					"type" : "null"
				}
			]
	  },
	  "completed" : {
		  "type" : "boolean"
	  }
  },
  "required" : ["_id", "description", "creation_timestamp", "completed"]
}
```

**Comment by rnowling-memphis** [comment]
It looks like this bug was fixed 3 weeks ago by @shohamroditimemphis:

https://github.com/memphisdev/memphis.py/blame/7458b6feafab95facc38f0258f8033c1d7973c66/memphis/producer.py#L236

A new version of the Python SDK hasn't been released or pushed to PyPI, however, so it's not available to our users.

**Comment by idanasulinmemphis** [comment]
Indeed, it will be released on our coming version of Python SDK, so I'm closing this one
